### PR TITLE
makeInstDirectory does not support vector masks or any other special fields

### PR DESCRIPTION
**Pull request by Shubhf**
I have tried to make changes for [https://github.com/sparcians/mavis/issues/15](Link) Pls suggest changes

### CODE REVIEW

**Review by klingaard — CHANGES_REQUESTED** [review]
This breaks the existing API for `makeInstDirectly` which in turn will break pretty much anyone out there who is currently using it.  In addition it requires the allocated `inst` object (type `InstType`) to understand/include an API call to `setSpecialFields`.

This begs the question, why can't you do this?  I.e. put the responsibility on the caller.
```
   auto inst = makeInstDirectly(.... old API ...);
   for(const auto& [field, value] :special_fields_map_){
            inst->setSpecialField(field.first,field.second);
   }
```

**Comment by klingaard** [comment]
@kathlenemagnus, @bdutro am I missing something?

**Comment by Shubhf** [comment]
Ok I ll check this out and get back to you.

**Comment by kathlenemagnus** [comment]
How about adding a new constructor type for the `ExtractorDirectInfo` class that takes in a map of special fields and their values? See [ExtractorDirectInfo.h#L242C1-L276C7](https://github.com/sparcians/mavis/blob/fe4a557091d5322ded4e090f10fca1e9e0b1704a/mavis/ExtractorDirectInfo.h#L242C1-L276C7)

Actually now that I look at this more closely, I do see a constructor that we could use:
```
ExtractorDirectInfo(const InstructionUniqueID uid, const RegListType &sources, const RegListType &dests,
                        const ValueListType& specials) :
        ExtractorDirectBase(uid), sources_(sources), dests_(dests), specials_(specials)
    {}
```

@Shubhf can you add a test for a vector add with a mask `vm` to see if this constructor will work?

**Comment by Shubhf** [comment]
yeah thats a good idea .. i ll try to implement it

**Comment by Shubhf** [comment]
@kathlenemagnus As you suggested to add a test vector with a mask "vm" to test to verify "ExtractorDirectInfo" , which will initialise "ExtractDirectInfo" with special fields including vm and validate that the mask is correctly set.

`void test_vector_add_with_mask_vm() {
    ExtractorDirectInfo ex_info(123, {1, 2}, {3}, {{mavis::ExtractorIF::SpecialField::VM, 0}});
    auto specials = ex_info.getSpecialFields();
    assert(specials.at(mavis::ExtractorIF::SpecialField::VM) == 0);
}`  

I have thought about this function suggest necessary changes

**Pull request closed without merging**
